clc
clear
close all

% ---------
% Plot Setup
% ---------
% Set Plot Width and FontSize
plot_width = 3.0;
aspect_ratio = 3/1; % 4:3 3:2 1:1
% Titel and Label Font size
font_size = 8.0;
% Legend font size
lfont_size = 6.0;
plot_height = plot_width * (1/aspect_ratio);
% Plot Line Widths
line_width = 1.1;
event_line_width = 0.5;
x_label_height = 0.17;


% load velocity command data which came from the following rosbag:
% ~/Desktop/rosbags/june_27/test7n_2018-06-27-03-09-07.bag
load('ml_vel_cmd_data.mat');

% Trim off everyting before IBVS mode was engaged at t=66.0 + 23.5 = 89.5 seconds in the
% rosbag and re-order because its in ENU
t = vel_cmd(1796:end,1);
vx = vel_cmd(1796:end,3);
vy = vel_cmd(1796:end,2);
vz = -vel_cmd(1796:end,4);
wz = -vel_cmd(1796:end,5);

% fix the time
t = t - t(1);
t = t + 23.35;

% Times when events took place starting the bag from t=66.0 seconds
t_wind_cal_start = 5.43;
t_wind_cal_stop = 15.43;
t_heading_cor = 19.45;
t_ibvs_outer = 23.5;
t_ibvs_inner = 42.6;
t_land_mode = 47.84;
t_land = 48.5;

t_end = 50;

figure('Units', 'inches', ...
       'Position', [0 0 plot_width plot_height], ...
       'PaperPositionMode', 'auto')

plot(t, vx, 'LineWidth', line_width)
hold on
plot([t_ibvs_inner; t_ibvs_inner], [-100; 100], '-.k', 'LineWidth', event_line_width)
plot([t_land_mode; t_land_mode], [-100; 100], '-.k', 'LineWidth', event_line_width)

% title('Marker Detection Rate vs Distance from Marker',...
%       'Interpreter', 'latex',...
%       'FontUnits', 'points',...
%       'FontSize', font_size,...
%       'FontName', 'Times')
  
% xlabel('Distance (m)',...
%        'Interpreter', 'latex',...
%        'FontUnits', 'points',...
%        'FontSize', font_size,...
%        'FontName', 'Times')
   
ylabel('$v_{\mathit{cmd}, x}$ (m/s)',...
       'Interpreter', 'latex',...
       'FontUnits', 'points',...
       'FontSize', font_size,...
       'FontName', 'Times')

% legend({'Outer', 'Inner'},...
%        'Interpreter', 'latex',...
%        'FontUnits', 'points',...
%        'FontSize', lfont_size,...
%        'FontName', 'Times',...
%        'Location', 'East',...
%        'Orientation', 'vertical',...
%        'Box', 'on')

axis([t_ibvs_outer, t_end, 0, 2])
set(gca, ...
    'YTick', 0:0.5:2,...
    'XTick', 25:5:t_end,...
    'FontSize', font_size,...
    'FontName', 'Times')
grid on


figure('Units', 'inches', ...
       'Position', [0 0 plot_width plot_height], ...
       'PaperPositionMode', 'auto')
plot(t, vy, 'LineWidth', line_width)
hold on
plot([t_ibvs_inner; t_ibvs_inner], [-100; 100], '-.k', 'LineWidth', event_line_width)
plot([t_land_mode; t_land_mode], [-100; 100], '-.k', 'LineWidth', event_line_width)

% title('Marker Detection Rate vs Distance from Marker',...
%       'Interpreter', 'latex',...
%       'FontUnits', 'points',...
%       'FontSize', font_size,...
%       'FontName', 'Times')
  
% xlabel('Distance (m)',...
%        'Interpreter', 'latex',...
%        'FontUnits', 'points',...
%        'FontSize', font_size,...
%        'FontName', 'Times')
   
ylabel('$v_{\mathit{cmd}, y}$ (m/s)',...
       'Interpreter', 'latex',...
       'FontUnits', 'points',...
       'FontSize', font_size,...
       'FontName', 'Times')

% legend({'Outer', 'Inner'},...
%        'Interpreter', 'latex',...
%        'FontUnits', 'points',...
%        'FontSize', lfont_size,...
%        'FontName', 'Times',...
%        'Location', 'East',...
%        'Orientation', 'vertical',...
%        'Box', 'on')

axis([t_ibvs_outer, t_end, -1, 1])
set(gca, ...
    'YTick', -1:0.5:1,...
    'XTick', 25:5:t_end,...
    'FontSize', font_size,...
    'FontName', 'Times')
grid on


figure('Units', 'inches', ...
       'Position', [0 0 plot_width plot_height], ...
       'PaperPositionMode', 'auto')
plot(t, vz, 'LineWidth', line_width)
hold on
plot([t_ibvs_inner; t_ibvs_inner], [-100; 100], '-.k', 'LineWidth', event_line_width)
plot([t_land_mode; t_land_mode], [-100; 100], '-.k', 'LineWidth', event_line_width)

% title('Marker Detection Rate vs Distance from Marker',...
%       'Interpreter', 'latex',...
%       'FontUnits', 'points',...
%       'FontSize', font_size,...
%       'FontName', 'Times')
  
% xlabel('Distance (m)',...
%        'Interpreter', 'latex',...
%        'FontUnits', 'points',...
%        'FontSize', font_size,...
%        'FontName', 'Times')
   
ylabel('$v_{\mathit{cmd}, z}$ (m/s)',...
       'Interpreter', 'latex',...
       'FontUnits', 'points',...
       'FontSize', font_size,...
       'FontName', 'Times')

% legend({'Outer', 'Inner'},...
%        'Interpreter', 'latex',...
%        'FontUnits', 'points',...
%        'FontSize', lfont_size,...
%        'FontName', 'Times',...
%        'Location', 'East',...
%        'Orientation', 'vertical',...
%        'Box', 'on')

axis([t_ibvs_outer, t_end, 0, 0.6])
set(gca, ...
    'YTick', 0:0.2:0.6,...
    'XTick', 25:5:t_end,...
    'FontSize', font_size,...
    'FontName', 'Times')
grid on


figure('Units', 'inches', ...
       'Position', [0 0 plot_width plot_height+x_label_height], ...
       'PaperPositionMode', 'auto')
plot(t, wz, 'LineWidth', line_width)
hold on
plot([t_ibvs_inner; t_ibvs_inner], [-100; 100], '-.k', 'LineWidth', event_line_width)
plot([t_land_mode; t_land_mode], [-100; 100], '-.k', 'LineWidth', event_line_width)

% title('Marker Detection Rate vs Distance from Marker',...
%       'Interpreter', 'latex',...
%       'FontUnits', 'points',...
%       'FontSize', font_size,...
%       'FontName', 'Times')
  
xlabel('Time (s)',...
       'Interpreter', 'latex',...
       'FontUnits', 'points',...
       'FontSize', font_size,...
       'FontName', 'Times')
   
ylabel('$\omega_{\mathit{cmd}, z}$ (rad/s)',...
       'Interpreter', 'latex',...
       'FontUnits', 'points',...
       'FontSize', font_size,...
       'FontName', 'Times')

% legend({'Outer', 'Inner'},...
%        'Interpreter', 'latex',...
%        'FontUnits', 'points',...
%        'FontSize', lfont_size,...
%        'FontName', 'Times',...
%        'Location', 'East',...
%        'Orientation', 'vertical',...
%        'Box', 'on')

axis([t_ibvs_outer, t_end, -0.2, 0.2])
set(gca, ...
    'YTick', -0.2:0.1:0.2,...
    'XTick', 25:5:t_end,...
    'FontSize', font_size,...
    'FontName', 'Times')
grid on

% Get default colors
% get(gca,'colororder')

%EXPORT FIGURE
% -Select the figure window you want to export
% -in command window:
%  print -depsc2 path2plotfile.eps
%