clc
clear
close all

% ---------
% Plot Setup
% ---------
% Set Plot Width and FontSize
plot_width = 6.0;
aspect_ratio = 8/3; % 4:3 3:2 1:1
% Titel and Label Font size
font_size = 10.0;
% Legend font size
lfont_size = 8.0;
plot_height = plot_width * (1/aspect_ratio);
% Plot Line Widths
line_width = 1.1;
event_line_width = 0.5;
x_label_height = 0.17;

load('vds_t_acc_gyro_data.mat')
load('nvds_t_acc_gyro_data.mat')

t_vds = vds_data(2543:end,1);
acc_x_vds = vds_data(2543:end,2);
acc_y_vds = vds_data(2543:end,3);
acc_z_vds = vds_data(2543:end,4);
t_vds = t_vds - t_vds(1);

t_nvds = nvds_data(2690:end,1);
acc_x_nvds = nvds_data(2690:end,2);
acc_y_nvds = nvds_data(2690:end,3);
acc_z_nvds = nvds_data(2690:end,4);
t_nvds = t_nvds - t_nvds(1);

% figure(1), clf
figure('Units', 'inches', ...
       'Position', [0 0 plot_width plot_height], ...
       'PaperPositionMode', 'auto')
   
   
subplot(1,2,2)
plot(t_vds, acc_z_vds)

% title('Marker Detection Rate vs Distance from Marker',...
%       'Interpreter', 'latex',...
%       'FontUnits', 'points',...
%       'FontSize', font_size,...
%       'FontName', 'Times')
  
xlabel('Time (s)',...
       'Interpreter', 'latex',...
       'FontUnits', 'points',...
       'FontSize', font_size,...
       'FontName', 'Times')
   
ylabel('Accel $z$ (m/s\textsuperscript{2})',...
       'Interpreter', 'latex',...
       'FontUnits', 'points',...
       'FontSize', font_size,...
       'FontName', 'Times')

% legend({'Outer', 'Inner'},...
%        'Interpreter', 'latex',...
%        'FontUnits', 'points',...
%        'FontSize', lfont_size,...
%        'FontName', 'Times',...
%        'Location', 'East',...
%        'Orientation', 'vertical',...
%        'Box', 'on')

axis([0, 25, -13, -6])
set(gca, ...
    'YTick', -13:1:-6,...
    'XTick', 0:5:25,...
    'FontSize', font_size,...
    'FontName', 'Times')
grid on




% % figure(1), clf
% figure('Units', 'inches', ...
%        'Position', [0 0 plot_width plot_height], ...
%        'PaperPositionMode', 'auto')
   
subplot(1,2,1)  
plot(t_nvds, acc_z_nvds)

% title('Marker Detection Rate vs Distance from Marker',...
%       'Interpreter', 'latex',...
%       'FontUnits', 'points',...
%       'FontSize', font_size,...
%       'FontName', 'Times')
  
xlabel('Time (s)',...
       'Interpreter', 'latex',...
       'FontUnits', 'points',...
       'FontSize', font_size,...
       'FontName', 'Times')
   
ylabel('Accel $z$ (m/s\textsuperscript{2})',...
       'Interpreter', 'latex',...
       'FontUnits', 'points',...
       'FontSize', font_size,...
       'FontName', 'Times')

% legend({'Outer', 'Inner'},...
%        'Interpreter', 'latex',...
%        'FontUnits', 'points',...
%        'FontSize', lfont_size,...
%        'FontName', 'Times',...
%        'Location', 'East',...
%        'Orientation', 'vertical',...
%        'Box', 'on')

axis([0, 25, -13, -6])
set(gca, ...
    'YTick', -13:1:-6,...
    'XTick', 0:5:25,...
    'FontSize', font_size,...
    'FontName', 'Times')
grid on

%EXPORT FIGURE
% -Select the figure window you want to export
% -in command window:
%  print -depsc2 path2plotfile.eps
%

